name: Publish to PyPi
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: upload release to PyPi
    if: github.repository == 'trustyai-explainability/llama-stack-provider-trustyai-garak'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/llama-stack-provider-trustyai-garak
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1