name: Publish to PyPi
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: upload release to PyPi
    if: github.repository == 'trustyai-explainability/llama-stack-provider-trustyai-garak'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/llama-stack-provider-trustyai-garak
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1