name: Publish to PyPi
on:
  release:
    types: [published]
jobs:
  pypi-publish:
    name: upload release to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/llama-stack-provider-trustyai-garak
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1